app/main/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, Email

class ContactForm(FlaskForm):
    name = StringField(u'Nama (*)', validators=[DataRequired(), Length(min=3, max=25)])
    company = StringField(u'Perusahaan')
    telp = StringField(u'Telepon (*)', validators=[DataRequired(), Length(min=10, max=16)])
    email = StringField(u'Email (*)', validators=[DataRequired(), Email()])
    message = TextAreaField(u'Pesan (*)', validators=[DataRequired(), Length(min=10, max=512)])
    submit = SubmitField(u'Kirim Pesan')
    recaptcha = RecaptchaField()

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__, static_folder="static", template_folder="templates")

from . import views, errors

app/main/views.py
import os
from flask import (
    render_template,
    session,
    redirect,
    url_for,
    flash,
    request,
    send_file,
    make_response,
    current_app,
)
from flask_mail import Message
from datetime import datetime
from sqlalchemy import or_
from io import BytesIO
from . import main
from .. import db, moment
from .forms import ContactForm
from ..models import Category, Contact, Product
from ..email import send_email
from config import Config
from datetime import timedelta


def product_data():
    return Category.query.limit(4).all()


@main.route("/")
def index():
    product = product_data()
    data = (
        db.session.query(
            Product.slug.label("product_slug"),
            Product.id,
            Product.title,
            Product.description,
            Product.description_html,
            Product.image_filename,
            Product.doc_filename,
            Category.name.label("category"),
            Category.slug.label("category_slug"),
        )
        .join(Category, Category.id == Product.category_id)
        .order_by(Product.create_on.desc())
        .limit(4)
    )
    return render_template("index.html", data=data, product=product)


@main.route("/tentang-kami")
def about():
    product = product_data()
    return render_template("about.html", product=product)


@main.route("/produk")
def category():
    data = Category.query.all()
    product = product_data()
    return render_template("products.html", data=data, product=product)


@main.route("/produk/<slug>", methods=["GET"])
def list_product(slug):
    category = db.session.query(Category.name, Category.description).filter(
        Category.slug == slug
    )
    data = (
        db.session.query(
            Product.slug.label("product_slug"),
            Product.id,
            Product.title,
            Product.description,
            Product.description_html,
            Product.image_filename,
            Product.doc_filename,
            Category.id,
            Category.name.label("category"),
            Category.description.label("category_desc"),
            Category.slug.label("category_slug"),
        )
        .join(Category, Category.id == Product.category_id)
        .filter(Category.slug == slug)
    )
    product = product_data()
    return render_template(
        "list_product.html", data=data, category=category, product=product
    )


@main.route("/produk/<slug1>/<slug2>", methods=["GET"])
def detail_product(slug1, slug2):
    file_data = (
        Product.query.join(Category)
        .filter(Category.slug == slug1, Product.slug == slug2)
        .first_or_404()
    )
    return send_file(
        BytesIO(file_data.doc_data),
        attachment_filename=file_data.doc_filename,
        mimetype="application/pdf",
    )


@main.route("/kontak", methods=["GET", "POST"])
def contact():
    product = product_data()
    form = ContactForm()
    if form.validate_on_submit():
        contact = Contact.query.filter(
            or_(Contact.email == form.email.data, Contact.telepon == form.telp.data)
        ).first()
        if contact is None:
            data = Contact(
                name=form.name.data,
                company=form.company.data,
                telepon=form.telp.data,
                email=form.email.data,
                message=form.message.data,
                datetime=datetime.now(),
            )
            db.session.add(data)
            db.session.commit()

            subject = "Pesan Dari Kontak Form [crowindojaya.com]"
            html = render_template(
                "email.html",
                email=data.email,
                tel=data.telepon,
                messages=data.message,
                create_on=data.create_on,
            )
            send_email(subject, html, data.email)

            flash("Pesan berhasil tersimpan. Kami akan segera menghubungi anda.")
            return redirect(url_for("main.contact"))
        else:
            flash("Email atau Nomor Telepon sudah terdaftar!")
    return render_template("contact.html", form=form, product=product)


@main.route("/robots.txt", methods=["GET"])
def robots():
    return "User-agent: *\nDisallow: /admin"


@main.route("/sitemap.xml", methods=["GET"])
def sitemap():
    try:
        """Generate sitemap.xml. Makes a list of urls and date modified."""
        pages = []
        ten_days_ago = (datetime.now() - timedelta(days=7)).date().isoformat()
        # static pages
        for rule in current_app.url_map.iter_rules():
            if "GET" in rule.methods and len(rule.arguments) == 0:
                pages.append(
                    ["https://www.crowindojaya.com" + str(rule.rule), ten_days_ago]
                )

        sitemap_xml = render_template("sitemap_template.xml", pages=pages)
        response = make_response(sitemap_xml)
        response.headers["Content-Type"] = "application/xml"

        return response
    except Exception as e:
        return str(e)

app/main/templates/about.html
{% extends 'main_base.html' %}
{% block head %}
<meta name="description"
    content="crowindojaya merupakan perusahaan yang bergerak di bidang produk disposable yang berdiri sejak 2010 di kota Yogyakarta. Produk-produk yang kami miliki antara lain adalah produk disposable">
<meta name="keyword" content="tentang crowindojaya, profile crowindojaya, crowindojaya jogja">
{% endblock %}
{% block title %}Tentang Crowindo Jaya{% endblock %}
{% block content %}
<div class="jumbotron background-header-about text-white">
    <div class="container">
        <h1 class="display-4"><strong>Tentang Kami</strong></h1>
        <h4>Kenal dengan kami, lebih dekat.</h4>
    </div>
</div>

<div class="container article py-4 text-center" id="historis">
    <h1><strong>Historis</strong></h1><br>
    <img src="{{ url_for('static', filename='images/logo-crowindo.png') }}" width="100" height="100" class="mx-auto"
        alt=""><br><br>
    <h5>CROWINDO JAYA merupakan perusahaan yang bergerak di bidang produk disposable, <br> berdiri pada tahun 2010 di
        Bantul Yogyakarta. Kami berkomitmen untuk menciptakan produk <br> dengan standar proteksi yang tinggi di
        industri makanan dan kesehatan</h5>
    <br>
</div>
<div class="container article py-4" id="visi-misi">
    <div class="row">
        <div class="col-md-6 col-sm-12 text-center">
            <h1><strong>Visi</strong></h1>
            <p>Menjadi perusahaan terbaik dan terbesar di bidang hygiene protection.</p>
        </div>
        <div class="col-md-6 col-sm-12 text-center">
            <h1><strong>Misi</strong></h1>
            <p>Mengutamakan kualitas untuk kepuasan pelanggan.
                <br> Memenuhi kebutuhan customer dengan standard internasional.
                <br> Berkembang dan tumbuh bersama mitra.
            </p>
        </div>
    </div>
</div>
<div class="container pt-4 pb-2">
    <div class="jumbotron background-contact-footer">
        <h1 class="display-4 text-white"><strong>Ajukan Kerjasama</strong></h1>
        <div class="">
            <a href="{{ url_for('main.contact') }}" class="btn btn-dark btn-lg my-2 mr-2">
                <span>Hubungi Kami</span>
            </a>
        </div>
    </div>
</div>
{% endblock %}

app/main/templates/contact.html
{% extends 'main_base.html' %}
{% block head %}
<meta name="description"
  content="Tertarik untuk kerjasama ? hubungi kami dan tanyakan produk yang ingin anda ketahui melalu WhatsApp, email maupun telepon.">
<meta name="keyword" content="kontak crowindojaya, alamat crowindojaya, crowindojaya jogja">
{% endblock %}
{% block title %}Kontak Kami{% endblock %}
{% block content %}
<div class="jumbotron background-header-contact text-white">
  <div class="container">
    <h1 class="display-4"><strong>Hubungi Kami</strong></h1>
    <h4>Kenal dengan kami, lebih dekat.</h4>
  </div>
</div>

<div class="container py-4">
  <h1 class="mb-5"><strong>Tinggalkan Pesan</strong></h1>
  <div class="row py-4">
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span>Narahubung</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">WhatsApp</h6>
            <a href="https://wa.me/681326540841?text=Saya%20tertarik%20untuk%20bekerja%20sama"><small
                class="text-muted">0813.2654.0841</small></a>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Telepon</h6>
            <a href="telp:+6281326540841"><small class="text-muted">0813.2654.0841</small></a><br>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Email</h6>
            <a href="mailto:widi@crowindojaya.com"><small class="text-muted">widi@crowindojaya.com</small></a>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <div>
            <h6 class="my-0">Alamat</h6>
            <small class="text-muted">Jipangan RT 04 Bangunjiwo Kasihan Bantul Yogyakarta</small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.387647012636!2d110.32574501414405!3d-7.854435994340837!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7af98022ac723d%3A0x1d9c7a7f84b27d48!2sCrowindojaya!5e0!3m2!1sid!2sid!4v1554036136557!5m2!1sid!2sid"
            width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        </li>
      </ul>
    </div>
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Kirim Pesan</h4>
      {% for message in get_flashed_messages() %}
      <div class="alert alert-dismissible fade show alert-dark" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <strong>{{ message }}</strong>
      </div>
      {% endfor %}
      <form method="POST">
        {{ form.hidden_tag() }}
        <div class="row">
          <div class="col-md-6 mb-3">
            {{ form.name.label() }} {{ name }}
            {{ form.name(class='form-control', placeholder='Nama Personal') }}
            {% if form.name.errors %}
            <small class="form-text text-danger">
              {% for error in form.name.errors %}
              {{ error }}
              {% endfor %}
            </small>
            {% endif%}
          </div>
          <div class="col-md-6 mb-3">
            {{ form.company.label() }} {{ company }}
            {{ form.company(class='form-control', placeholder='Nama Perusahaan') }}
            {% if form.company.errors %}
            <small class="form-text text-danger">
              {% for error in form.company.errors %}
              {{ error }}
              {% endfor %}
            </small>
            {% endif%}
          </div>
        </div>

        <div class="mb-3">
          {{ form.telp.label() }} {{ telepon }}
          {{ form.telp(class='form-control', placeholder='Nomor Telepon') }}
          {% if form.telp.errors %}
          <small class="form-text text-danger">
            {% for error in form.telp.errors %}
            {{ error }}
            {% endfor %}
          </small>
          {% endif%}
        </div>

        <div class="mb-3">
          {{ form.email.label() }} {{ email }}
          {{ form.email(class='form-control', placeholder='email@domain.com') }}
          {% if form.email.errors %}
          <small class="form-text text-danger">
            {% for error in form.email.errors %}
            {{ error }}
            {% endfor %}
          </small>
          {% endif%}
        </div>

        <div class="mb-3">
          {{ form.message.label() }} {{ message }}
          {{ form.message(class='form-control', placeholder='Pesan Anda', rows=5) }}
          {% if form.message.errors %}
          <small class="form-text text-danger">
            {% for error in form.message.errors %}
            {{ error }}
            {% endfor %}
          </small>
          {% endif%}
        </div>
        {{ form.recaptcha }}
        <hr class="mb-4">
        {{ form.submit(class='btn btn-primary btn-lg btn-block') }}

      </form>
    </div>
  </div>
</div>
{% endblock %}

app/main/templates/includes/footer.html
<hr>    
<footer class="site-footer mt-5">
        <div class="container">
            <div class="row justify-content-md-between">
                <div class="col-sm-12 col-md-4 mb-4">
                    <h3 class="h5 mb-3">Crowindo Jaya</h3>
                    <p class="text-muted">Merupakan perusahaan yang bergerak di bidang produk disposable, berdiri pada tahun 2010 di Bantul Yogyakarta.</p>
                </div>
                <div class="col-4 col-md-2 mb-4">
                    <h3 class="h5 mb-3">Tentang Kami</h3>
                    <ul class="nav flex-column">
                        <li class="mb-1"><a href="{{ url_for('main.about') }}#historis" class="text-muted">Historis</a></li>
                        <li class="mb-1"><a href="{{ url_for('main.about') }}#visi-misi" class="text-muted">Visi & Misi</a></li>
                        <li class="mb-1"><a href="{{ url_for('main.contact') }}" class="text-muted">Kerjasama</a></li>
                    </ul>
                </div>
                <div class="col-4 col-md-2 mb-4">
                    <h3 class="h5 mb-3">Produk Kami</h3>
                    <ul class="nav flex-column">
                        {% for product in product %}
                            <li class="mb-1"><a href="{{ url_for('main.list_product', slug=product.slug) }}" class="text-muted">{{ product.name | title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-4 col-md-2 mb-4">
                    <h3 class="h5 mb-3">Narahubung</h3>
                    <ul class="nav flex-column">
                        <li class="mb-1"><a href="https://wa.me/6289657990968?text=Saya%20tertarik%20untuk%20bekerja%20sama" class="text-muted">WhatsApp</a></li>
                        <li class="mb-1"><a href="telp:+6281326540841" class="text-muted">Telepon</a></li>
                        <li class="mb-1"><a href="mailto:widi@crowindojaya.com" class="text-muted">Email</a></li>
                    </ul>
                </div>
            </div>

            <hr class="m-0">

            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-center mt-4">
                <p class="small text-muted">© Crowindo Jaya {{ moment().format('YYYY') }}</p>
                <ul class="list-inline">
                  <li class="list-inline-item">
                      <a href="https://wa.me/6289657990968?text=Saya%20tertarik%20untuk%20bekerja%20sama"><img src="{{ url_for('static', filename='images/whatsapp.svg') }}" alt="WhatsApp" class="icon-lg"></a>
                  </li>
                  <li class="list-inline-item">
                      <a href="https://fb.me/crowindo_jaya" target="_blank"><img src="{{ url_for('static', filename='images/facebook.svg') }}" alt="WhatsApp" class="icon-lg"></a>
                  </li>
                  <li class="list-inline-item">
                      <a href="https://instagram.com/crowindo_jaya" target="_blank"><img src="{{ url_for('static', filename='images/instagram.svg') }}" alt="WhatsApp" class="icon-lg"></a>
                  </li>
              </ul>
            </div>
        </div>
</footer>

<a href="https://wa.me/6289657990968?text=Saya%20tertarik%20untuk%20bekerja%20sama" class="float-button text-white" data-toggle="tooltip" data-placement="bottom" title="Chat with Us">
    <i class="fab fa-2x fa-whatsapp my-float-button"></i>
</a>

app/main/templates/includes/message.html
<div class="container">
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}
</div>

app/main/templates/includes/navbar.html
<div class="container" id="navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-white my-3">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='images/logo-crowindo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
              Crowindo Jaya
            </a>
          
            <div class="collapse navbar-collapse right" id="navbarTogglerDemo02">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.category') }}">Produk Kami</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.about') }}">Tentang Kami</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.contact') }}">Hubungi Kami</a>
                  </li>
              </ul>
            </div>
        </nav>
</div>

app/main/templates/index.html
{% extends 'main_base.html' %}
{% block title %}Beranda{% endblock %}
{% block content %}
<div class="jumbotron background-header-home text-white">
  <div class="container">
    <h1><strong>
        <p>Crowindojaya.com <br> Produsen Produk Disposable
      </strong></h1>
    <h4>Menawarkan berbagai macam produk Disposable</h4>
    <div class="mt-4">
      {#<a href="{{ url_for('main.list_product') }}"
               class="btn btn-dark btn-lg my-2 mr-2">
              <span>Produk Kami</span>
            </a>#}
    </div>
  </div>
</div>

<div class="container article py-4">
  <div class="d-flex justify-content-center mb-4">
    <h1 class="font-weight-bold">Produk Kami</h1>
  </div>
  <div class="row">
    {% for data in data %}
    <div class="col-lg-3 col-md-6 col-sm-12 mb-5">
      <div class="card">
        <img class="card-img-top" src="{{ url_for('admin.load_image_product', filename=data.image_filename) }}"
          alt="{{ data.image_filename }}">
        <div class="card-body">
          <h4 class="card-title">{{ data.title | title }}</h4>
          <div class="card-text mb-3">
            {% if data.description_html %}
            {{ data.description_html | safe }}
            {% else %}
            {{ data.description }}
            {% endif %}
          </div>
          {% if data.doc_filename is not none %}<a
            href="{{ url_for('main.detail_product', slug1=data.category_slug, slug2=data.product_slug) }}"
            class="btn btn-dark" target="_blank">Detail Produk</a>{% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!--
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner row w-100 mx-auto">
          {% for data in data %}
              <div class="carousel-item col-lg-3 col-md-6 col-sm-12 mb-5">
                  <div class="card">
                      <img class="card-img-top" src="{{ url_for('admin.static', filename='uploads/photos/'+data.image_filename) }}" alt="{{ data.image_filename }}">
                      <div class="card-body">
                      <h4 class="card-title">{{ data.title | title }}</h4>
                      <div class="card-text mb-3">
                          {% if data.description_html %}
                              {{ data.description_html | safe }}
                          {% else %}
                              {{ data.description }}
                          {% endif %}
                      </div>
                      {% if data.doc_filename is not none %}<a href="{{ url_for('main.detail_product', slug1=data.category_slug, slug2=data.product_slug) }}" class="btn btn-dark" target="_blank">Detail Produk</a>{% endif %}
                      </div>
                  </div>              
              </div>
          {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>-->
</div>

<div class="container pt-4 pb-2">
  <div class="jumbotron background-contact-footer">
    <h1 class="display-4 text-white"><strong>Ajukan Kerjasama</strong></h1>
    <div class="">
      <a href="{{ url_for('main.contact') }}" class="btn btn-dark btn-lg my-2 mr-2">
        <span>Hubungi Kami</span>
      </a>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}
<script>
  $(document).ready(function () {
    $(".carousel-inner .carousel-item").first().addClass("active");
    $("#myCarousel").on("slide.bs.carousel", function (e) {
      var $e = $(e.relatedTarget);
      var idx = $e.index();
      var itemsPerSlide = 4;
      var totalItems = $(".carousel-item").length;

      if (idx >= totalItems - (itemsPerSlide - 1)) {
        var it = itemsPerSlide - (totalItems - idx);
        for (var i = 0; i < it; i++) {
          // append slides to end
          if (e.direction == "left") {
            $(".carousel-item")
              .eq(i)
              .appendTo(".carousel-inner");
          } else {
            $(".carousel-item")
              .eq(0)
              .appendTo($(this).find(".carousel-inner"));
          }
        }
      }
    });
  });
</script>
{% endblock %}

app/main/templates/list_product.html
{% extends 'main_base.html' %}
{% block head %}
<meta name="description" content="{%if category%}{{ category.0.description | title }}{%endif%}">
<meta name="keyword"
    content="jual disposable di jogja, jual spounbond di jogja, coat sekali pakai, jual Coverall produk disposable, produk crowindojaya">
{% endblock %}
{% block title %}Daftar Produk {%if category%}{{ category.0.name | title }}{%endif%}{% endblock %}
{% block content %}
<div class="container article py-5 text-center" id="produk">
    {%- for category in category %}
    <h1><strong>{{ category.name | title }}</strong></h1>
    <p>{{ category.description }}</p>
    {% endfor -%}
</div>
<div class="container article py-4">
    <div class="row">
        {%- for data in data %}
        <div class="col-md-6 col-sm-12 mb-5">
            <div class="card">
                <img class="card-img-top" src="{{ url_for('admin.load_image_product', filename=data.image_filename) }}"
                    alt="{{ data.image_filename }}">
                <div class="card-body">
                    <h4 class="card-title">{{ data.title | title }}</h4>
                    <div class="card-text mb-3">
                        {% if data.description_html %}
                        {{ data.description_html | safe }}
                        {% else %}
                        {{ data.description }}
                        {% endif %}
                    </div>
                    {% if data.doc_filename is not none %}<a
                        href="{{ url_for('main.detail_product', slug1=data.category_slug, slug2=data.product_slug) }}"
                        class="btn btn-dark" target="_blank">Detail Produk</a>{% endif %}
                </div>
            </div>
        </div>
        {% endfor -%}
    </div>
</div>
{% endblock %}

app/main/templates/main_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {%- block head %}
  <meta name="description"
    content="Crowindojaya merupakan perusahaan yang bergerak di bidang produk disposable, menjual produk disposable dan spounbond di jogja">
  <meta name="keyword"
    content="jual disposable di jogja, jual spounbond di jogja, coat sekali pakai, Coverall disposable, crowindojaya">
  {% endblock -%}
  <meta name="robots" content="index, follow">
  <meta property="og:title" content="Crowindo Jaya">
  <meta property="og:description"
    content="Crowindojaya merupakan perusahaan yang bergerak di bidang produk disposable, menjual produk disposable dan spounbond di jogja">
  <meta property="og:image" content="{{ url_for('static', filename='images/backgournd-crowindo.jpg') }}">
  <meta property="og:url" content="{{ url_for('main.index') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
  <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
  <title>{%- block title %}{% endblock %} | Crowindo Jaya</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap4-business-tycoon.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/custome.css') }}">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137381654-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-137381654-1');
  </script>
</head>

<body>
  {%- include 'includes/navbar.html' %}
  {%- block content %}{% endblock %}
  {%- include 'includes/footer.html' %}
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.slim.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    }); {
      {
        moment.include_jquery()
      }
    } {
      {
        moment.include_moment()
      }
    } {
      {
        moment.locale("id")
      }
    }
  </script>
  {%- block script %}{% endblock %}
</body>

</html>

app/main/templates/products.html
{% extends 'main_base.html' %}
{% block head %}
<meta name="description"
    content="crowindojaya menjual produk-produk disposable seperti coat, coverall serta shoes cover dan juga menjual produk spounbond di jogja, dan melayani pengiriman seluruh indonesia.">
<meta name="keyword"
    content="jual disposable di jogja, jual spounbond di jogja, coat sekali pakai, jual Coverall produk disposable, produk crowindojaya">
{% endblock %}
{% block title %}Produk Kami{% endblock %}
{% block content %}
<div class="container article py-5 text-center" id="produk">
    <h1><strong>Kategori Produk</strong></h1>
    <p>Berikut ini kategori produk dari kami.</p>
</div>
<div class="container article py-4">
    <div class="row">
        {% for data in data %}
        <div class="col-md-6 col-sm-12 mb-5">
            <div class="card">
                <img class="card-img-top" src="{{ url_for('admin.load_image_category', filename=data.image_filename) }}"
                    alt="{{ data.image_filename }}">
                <div class="card-body">
                    <h4 class="card-title">{{ data.name | title }}</h4>
                    <p class="card-text">{{ data.description }}</p>
                    <a href="{{ url_for('main.list_product', slug=data.slug) }}" class="btn btn-dark">Detail Produk</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}